ekf_slam:
  std_motion_xy: 0.05 #0.01
  std_motion_theta: 1 #0.5

  std_sensor_range: 0.04 #0.04
  std_sensor_bearing: 1 #1 #degrees

  std_new_landmark: 1
  mahalanobis_threshold: 5.991 # 5.991 = 95% confidence
  frequency: 15.0
  uncertainty_scale: 5 # scale visualization of landmark covariances
  verbose: false # true/false
